LAMMPS (2 Jul 2021)
# REAX potential for Nitroamines system
# .....

units		real

atom_style	charge
read_data	data.AB
Reading data file ...
  orthogonal box = (0.0000000 0.0000000 0.0000000) to (25.000000 25.000000 25.000000)
  2 by 2 by 2 MPI processor grid
  reading atoms ...
  104 atoms
  read_data CPU = 0.002 seconds

pair_style	reax/c lmp_control
WARNING: Ignoring inactive control parameter: simulation_name (src/REAXFF/reaxff_control.cpp:97)
WARNING: Ignoring inactive control parameter: energy_update_freq (src/REAXFF/reaxff_control.cpp:97)
WARNING: Support for writing native trajectories has been removed after LAMMPS version 8 April 2021 (src/REAXFF/reaxff_control.cpp:113)
WARNING: Ignoring inactive control parameter: traj_title (src/REAXFF/reaxff_control.cpp:97)
WARNING: Ignoring inactive control parameter: atom_info (src/REAXFF/reaxff_control.cpp:97)
WARNING: Ignoring inactive control parameter: atom_forces (src/REAXFF/reaxff_control.cpp:97)
WARNING: Ignoring inactive control parameter: atom_velocities (src/REAXFF/reaxff_control.cpp:97)
WARNING: Ignoring inactive control parameter: bond_info (src/REAXFF/reaxff_control.cpp:97)
WARNING: Ignoring inactive control parameter: angle_info (src/REAXFF/reaxff_control.cpp:97)
pair_coeff	* * ffield.reax.AB H B N
Reading potential file ffield.reax.AB with DATE: 2011-02-18
WARNING: Changed valency_val to valency_boc for X (src/REAXFF/reaxff_ffield.cpp:294)

neighbor	2 bin
neigh_modify	every 10 delay 0 check no

fix		1 all nve
fix             2 all qeq/reax 1 0.0 10.0 1e-6 param.qeq
fix             3 all temp/berendsen 500.0 500.0 100.0

timestep	0.25

#dump		1 all atom 30 dump.reax.ab

run		3000

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Your simulation uses code contributions which should be cited:

- pair reaxff command:

@Article{Aktulga12,
 author = {H. M. Aktulga, J. C. Fogarty, S. A. Pandit, A. Y. Grama},
 title = {Parallel reactive molecular dynamics: Numerical methods and algorithmic techniques},
 journal = {Parallel Computing},
 year =    2012,
 volume =  38,
 pages =   {245--259}
}

- fix qeq/reaxff command:

@Article{Aktulga12,
 author = {H. M. Aktulga, J. C. Fogarty, S. A. Pandit, A. Y. Grama},
 title = {Parallel reactive molecular dynamics: Numerical methods and algorithmic techniques},
 journal = {Parallel Computing},
 year =    2012,
 volume =  38,
 pages =   {245--259}
}

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Neighbor list info ...
  update every 10 steps, delay 0 steps, check no
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 12
  ghost atom cutoff = 12
  binsize = 6, bins = 5 5 5
  2 neighbor lists, perpetual/occasional/extra = 2 0 0
  (1) pair reax/c, perpetual
      attributes: half, newton off, ghost
      pair build: half/bin/newtoff/ghost
      stencil: full/ghost/bin/3d
      bin: standard
  (2) fix qeq/reax, perpetual, copy from (1)
      attributes: half, newton off, ghost
      pair build: copy
      stencil: none
      bin: none
Per MPI rank memory allocation (min/avg/max) = 9.558 | 10.17 | 10.77 Mbytes
Step Temp E_pair E_mol TotEng Press 
       0            0   -8505.1816            0   -8505.1816   -673.36566 
    3000    503.67331    -8411.297            0   -8256.6575    154.86364 
Loop time of 7.71063 on 8 procs for 3000 steps with 104 atoms

Performance: 8.404 ns/day, 2.856 hours/ns, 389.073 timesteps/s
99.7% CPU use with 8 MPI tasks x no OpenMP threads

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 2.7234     | 3.4501     | 4.0451     |  21.5 | 44.74
Neigh   | 0.1556     | 0.17292    | 0.20252    |   3.4 |  2.24
Comm    | 0.77114    | 1.3667     | 2.0954     |  34.3 | 17.73
Output  | 7.2023e-05 | 7.8329e-05 | 0.00011063 |   0.0 |  0.00
Modify  | 2.6876     | 2.7167     | 2.7329     |   0.8 | 35.23
Other   |            | 0.004155   |            |       |  0.05

Nlocal:        13.0000 ave          23 max           5 min
Histogram: 2 1 0 1 0 0 2 1 0 1
Nghost:        324.875 ave         377 max         272 min
Histogram: 1 0 1 2 1 0 1 0 0 2
Neighs:        465.125 ave         791 max         132 min
Histogram: 1 1 1 1 0 0 1 1 1 1

Total # of neighbors = 3721
Ave neighs/atom = 35.778846
Neighbor list builds = 300
Dangerous builds not checked
Total wall time: 0:00:07
