LAMMPS (4 Jan 2019)
# REAX potential for Nitroamines system
# .....

units		real

atom_style	charge
read_data	data.AB
  orthogonal box = (0 0 0) to (25 25 25)
  2 by 2 by 2 MPI processor grid
  reading atoms ...
  104 atoms

pair_style	reax/c lmp_control
pair_coeff	* * ffield.reax.AB H B N
Reading potential file ffield.reax.AB with DATE: 2011-02-18

neighbor	2 bin
neigh_modify	every 10 delay 0 check no

fix		1 all nve
fix             2 all qeq/reax 1 0.0 10.0 1e-6 param.qeq
fix             3 all temp/berendsen 500.0 500.0 100.0

timestep	0.25

#dump		1 all atom 30 dump.reax.ab

run		3000
Neighbor list info ...
  update every 10 steps, delay 0 steps, check no
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 12
  ghost atom cutoff = 12
  binsize = 6, bins = 5 5 5
  2 neighbor lists, perpetual/occasional/extra = 2 0 0
  (1) pair reax/c, perpetual
      attributes: half, newton off, ghost
      pair build: half/bin/newtoff/ghost
      stencil: half/ghost/bin/3d/newtoff
      bin: standard
  (2) fix qeq/reax, perpetual, copy from (1)
      attributes: half, newton off, ghost
      pair build: copy
      stencil: none
      bin: none
Per MPI rank memory allocation (min/avg/max) = 10.6 | 11.32 | 12.12 Mbytes
Step Temp E_pair E_mol TotEng Press 
       0            0   -8505.1816            0   -8505.1816   -673.36566 
    3000    478.88626   -8408.6983            0    -8261.669    624.36114 
Loop time of 6.09911 on 8 procs for 3000 steps with 104 atoms

Performance: 10.624 ns/day, 2.259 hours/ns, 491.875 timesteps/s
99.7% CPU use with 8 MPI tasks x no OpenMP threads

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 3.798      | 3.8254     | 3.864      |   1.0 | 62.72
Neigh   | 0.089364   | 0.11314    | 0.13984    |   4.7 |  1.86
Comm    | 0.09528    | 0.13136    | 0.16079    |   5.3 |  2.15
Output  | 2.8219e-05 | 3.1733e-05 | 4.402e-05  |   0.0 |  0.00
Modify  | 1.9985     | 2.0273     | 2.0532     |   1.2 | 33.24
Other   |            | 0.001876   |            |       |  0.03

Nlocal:    13 ave 22 max 5 min
Histogram: 2 1 0 0 1 0 2 1 0 1
Nghost:    319.25 ave 369 max 269 min
Histogram: 1 0 1 1 2 0 1 0 1 1
Neighs:    461.375 ave 735 max 128 min
Histogram: 1 1 0 1 0 1 0 1 2 1

Total # of neighbors = 3691
Ave neighs/atom = 35.4904
Neighbor list builds = 300
Dangerous builds not checked

Please see the log.cite file for references relevant to this simulation

Total wall time: 0:00:06
