LAMMPS (30 Jul 2021)
# REAX potential for Nitroamines system
# .....

units		real

atom_style	charge
read_data	data.AB
Reading data file ...
  orthogonal box = (0.0000000 0.0000000 0.0000000) to (25.000000 25.000000 25.000000)
  2 by 2 by 2 MPI processor grid
  reading atoms ...
  104 atoms
  read_data CPU = 0.002 seconds

pair_style	reax/c lmp_control
WARNING: Ignoring inactive control parameter: simulation_name (src/REAXFF/reaxff_control.cpp:97)
WARNING: Ignoring inactive control parameter: energy_update_freq (src/REAXFF/reaxff_control.cpp:97)
WARNING: Support for writing native trajectories has been removed after LAMMPS version 8 April 2021 (src/REAXFF/reaxff_control.cpp:113)
WARNING: Ignoring inactive control parameter: traj_title (src/REAXFF/reaxff_control.cpp:97)
WARNING: Ignoring inactive control parameter: atom_info (src/REAXFF/reaxff_control.cpp:97)
WARNING: Ignoring inactive control parameter: atom_forces (src/REAXFF/reaxff_control.cpp:97)
WARNING: Ignoring inactive control parameter: atom_velocities (src/REAXFF/reaxff_control.cpp:97)
WARNING: Ignoring inactive control parameter: bond_info (src/REAXFF/reaxff_control.cpp:97)
WARNING: Ignoring inactive control parameter: angle_info (src/REAXFF/reaxff_control.cpp:97)
pair_coeff	* * ffield.reax.AB H B N
Reading potential file ffield.reax.AB with DATE: 2011-02-18
WARNING: Changed valency_val to valency_boc for X (src/REAXFF/reaxff_ffield.cpp:294)

neighbor	2 bin
neigh_modify	every 10 delay 0 check no

fix		1 all nve
fix             2 all qeq/reax 1 0.0 10.0 1e-6 param.qeq
fix             3 all temp/berendsen 500.0 500.0 100.0

timestep	0.25

#dump		1 all atom 30 dump.reax.ab

run		3000

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Your simulation uses code contributions which should be cited:

- pair reaxff command:

@Article{Aktulga12,
 author = {H. M. Aktulga, J. C. Fogarty, S. A. Pandit, A. Y. Grama},
 title = {Parallel reactive molecular dynamics: Numerical methods and algorithmic techniques},
 journal = {Parallel Computing},
 year =    2012,
 volume =  38,
 pages =   {245--259}
}

- fix qeq/reaxff command:

@Article{Aktulga12,
 author = {H. M. Aktulga, J. C. Fogarty, S. A. Pandit, A. Y. Grama},
 title = {Parallel reactive molecular dynamics: Numerical methods and algorithmic techniques},
 journal = {Parallel Computing},
 year =    2012,
 volume =  38,
 pages =   {245--259}
}

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Neighbor list info ...
  update every 10 steps, delay 0 steps, check no
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 12
  ghost atom cutoff = 12
  binsize = 6, bins = 5 5 5
  2 neighbor lists, perpetual/occasional/extra = 2 0 0
  (1) pair reax/c, perpetual
      attributes: half, newton off, ghost
      pair build: half/bin/newtoff/ghost
      stencil: full/ghost/bin/3d
      bin: standard
  (2) fix qeq/reax, perpetual, copy from (1)
      attributes: half, newton off, ghost
      pair build: copy
      stencil: none
      bin: none
Per MPI rank memory allocation (min/avg/max) = 9.558 | 10.17 | 10.77 Mbytes
Step Temp E_pair E_mol TotEng Press 
       0            0   -8505.1816            0   -8505.1816   -673.36566 
    3000    507.48428   -8415.6577            0   -8259.8481    984.83509 
Loop time of 5.06141 on 8 procs for 3000 steps with 104 atoms

Performance: 12.803 ns/day, 1.875 hours/ns, 592.720 timesteps/s
99.9% CPU use with 8 MPI tasks x no OpenMP threads

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 2.0491     | 2.395      | 2.7874     |  17.0 | 47.32
Neigh   | 0.10388    | 0.12318    | 0.14387    |   3.8 |  2.43
Comm    | 0.15107    | 0.54466    | 0.89067    |  35.7 | 10.76
Output  | 6.8914e-05 | 7.372e-05  | 0.00010443 |   0.0 |  0.00
Modify  | 1.977      | 1.9965     | 2.0149     |   0.9 | 39.45
Other   |            | 0.001945   |            |       |  0.04

Nlocal:        13.0000 ave          23 max           5 min
Histogram: 1 2 0 1 0 0 3 0 0 1
Nghost:        324.875 ave         377 max         273 min
Histogram: 1 0 1 2 1 0 1 0 0 2
Neighs:        466.750 ave         780 max         129 min
Histogram: 1 1 1 0 1 0 1 1 1 1

Total # of neighbors = 3734
Ave neighs/atom = 35.903846
Neighbor list builds = 300
Dangerous builds not checked
Total wall time: 0:00:05
