LAMMPS (2 Aug 2023 - Development - bc02a7cc6)
# REAX potential for Nitroamines system
# .....

units		real

atom_style	charge
read_data	data.AB
Reading data file ...
  orthogonal box = (0 0 0) to (25 25 25)
  2 by 2 by 2 MPI processor grid
  reading atoms ...
  104 atoms
  read_data CPU = 0.002 seconds

pair_style	reax/c lmp_control
WARNING: Ignoring inactive control parameter: simulation_name (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: energy_update_freq (src/REAXFF/reaxff_control.cpp:98)
WARNING: Support for writing native trajectories has been removed after LAMMPS version 8 April 2021 (src/REAXFF/reaxff_control.cpp:114)
WARNING: Ignoring inactive control parameter: traj_title (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: atom_info (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: atom_forces (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: atom_velocities (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: bond_info (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: angle_info (src/REAXFF/reaxff_control.cpp:98)
pair_coeff	* * ffield.reax.AB H B N
Reading potential file ffield.reax.AB with DATE: 2011-02-18
WARNING: Changed valency_val to valency_boc for X (src/REAXFF/reaxff_ffield.cpp:296)

neighbor	2 bin
neigh_modify	every 10 delay 0 check no

fix		1 all nve
fix             2 all qeq/reax 1 0.0 10.0 1e-6 param.qeq
fix             3 all temp/berendsen 500.0 500.0 100.0

timestep	0.25

#dump		1 all atom 30 dump.reax.ab

run		3000

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Your simulation uses code contributions which should be cited:

- pair reaxff command: doi:10.1016/j.parco.2011.08.005

@Article{Aktulga12,
 author = {H. M. Aktulga and J. C. Fogarty and S. A. Pandit and A. Y. Grama},
 title = {Parallel Reactive Molecular Dynamics: {N}umerical Methods and Algorithmic Techniques},
 journal = {Parallel Computing},
 year =    2012,
 volume =  38,
 number =  {4--5},
 pages =   {245--259}
}

- fix qeq/reaxff command: doi:10.1016/j.parco.2011.08.005

@Article{Aktulga12,
 author = {H. M. Aktulga and J. C. Fogarty and S. A. Pandit and A. Y. Grama},
 title = {Parallel Reactive Molecular Dynamics: {N}umerical Methods and Algorithmic Techniques},
 journal = {Parallel Computing},
 year =    2012,
 volume =  38,
 pages =   {245--259}
}

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Neighbor list info ...
  update: every = 10 steps, delay = 0 steps, check = no
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 12
  ghost atom cutoff = 12
  binsize = 6, bins = 5 5 5
  2 neighbor lists, perpetual/occasional/extra = 2 0 0
  (1) pair reax/c, perpetual
      attributes: half, newton off, ghost
      pair build: half/bin/newtoff/ghost
      stencil: full/ghost/bin/3d
      bin: standard
  (2) fix qeq/reax, perpetual, copy from (1)
      attributes: half, newton off
      pair build: copy
      stencil: none
      bin: none
Per MPI rank memory allocation (min/avg/max) = 9.558 | 10.17 | 10.77 Mbytes
   Step          Temp          E_pair         E_mol          TotEng         Press     
         0   0             -8505.1816      0             -8505.1816     -673.36566    
      3000   523.37935     -8414.2797      0             -8253.5899      2189.7574    
Loop time of 6.97296 on 8 procs for 3000 steps with 104 atoms

Performance: 9.293 ns/day, 2.583 hours/ns, 430.233 timesteps/s, 44.744 katom-step/s
99.9% CPU use with 8 MPI tasks x no OpenMP threads

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 2.3688     | 2.8806     | 3.3295     |  18.1 | 41.31
Neigh   | 0.15784    | 0.18832    | 0.22582    |   4.6 |  2.70
Comm    | 0.48849    | 0.93618    | 1.449      |  31.8 | 13.43
Output  | 0.00010473 | 0.00010999 | 0.0001359  |   0.0 |  0.00
Modify  | 2.926      | 2.9617     | 2.9932     |   1.2 | 42.47
Other   |            | 0.006041   |            |       |  0.09

Nlocal:             13 ave          23 max           5 min
Histogram: 1 2 0 1 0 0 3 0 0 1
Nghost:          321.5 ave         371 max         275 min
Histogram: 1 0 1 3 0 0 1 0 0 2
Neighs:        466.625 ave         790 max         136 min
Histogram: 1 1 1 1 0 0 1 2 0 1

Total # of neighbors = 3733
Ave neighs/atom = 35.894231
Neighbor list builds = 300
Dangerous builds not checked
Total wall time: 0:00:07
