LAMMPS (29 Aug 2024 - Development - f820c928a)
# REAX potential for Nitroamines system
# .....

units		real

atom_style	charge
read_data	data.AB
Reading data file ...
  orthogonal box = (0 0 0) to (25 25 25)
  2 by 2 by 2 MPI processor grid
  reading atoms ...
  104 atoms
  read_data CPU = 0.004 seconds

pair_style	reaxff lmp_control
WARNING: Ignoring inactive control parameter: simulation_name (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: energy_update_freq (src/REAXFF/reaxff_control.cpp:98)
WARNING: Support for writing native trajectories has been removed after LAMMPS version 8 April 2021 (src/REAXFF/reaxff_control.cpp:114)
WARNING: Ignoring inactive control parameter: traj_title (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: atom_info (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: atom_forces (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: atom_velocities (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: bond_info (src/REAXFF/reaxff_control.cpp:98)
WARNING: Ignoring inactive control parameter: angle_info (src/REAXFF/reaxff_control.cpp:98)
pair_coeff	* * ffield.reax.AB H B N
Reading potential file ffield.reax.AB with DATE: 2011-02-18
WARNING: Changed valency_val to valency_boc for X (src/REAXFF/reaxff_ffield.cpp:294)

neighbor	2 bin
neigh_modify	every 10 delay 0 check no

fix		1 all nve
fix             2 all qeq/reax 1 0.0 10.0 1e-6 param.qeq
fix             3 all temp/berendsen 500.0 500.0 100.0

timestep	0.25

#dump		1 all atom 30 dump.reax.ab

run		3000

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Your simulation uses code contributions which should be cited:

- Type Label Framework: https://doi.org/10.1021/acs.jpcb.3c08419

@Article{Gissinger24,
 author = {Jacob R. Gissinger, Ilia Nikiforov, Yaser Afshar, Brendon Waters, Moon-ki Choi, Daniel S. Karls, Alexander Stukowski, Wonpil Im, Hendrik Heinz, Axel Kohlmeyer, and Ellad B. Tadmor},
 title = {Type Label Framework for Bonded Force Fields in LAMMPS},
 journal = {J. Phys. Chem. B},
 year =    2024,
 volume =  128,
 number =  13,
 pages =   {3282--3297}
}

- pair reaxff command: doi:10.1016/j.parco.2011.08.005

@Article{Aktulga12,
 author = {H. M. Aktulga and J. C. Fogarty and S. A. Pandit and A. Y. Grama},
 title = {Parallel Reactive Molecular Dynamics: {N}umerical Methods and Algorithmic Techniques},
 journal = {Parallel Computing},
 year =    2012,
 volume =  38,
 number =  {4--5},
 pages =   {245--259}
}

- fix qeq/reaxff command: doi:10.1016/j.parco.2011.08.005

@Article{Aktulga12,
 author = {H. M. Aktulga and J. C. Fogarty and S. A. Pandit and A. Y. Grama},
 title = {Parallel Reactive Molecular Dynamics: {N}umerical Methods and Algorithmic Techniques},
 journal = {Parallel Computing},
 year =    2012,
 volume =  38,
 pages =   {245--259}
}

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Neighbor list info ...
  update: every = 10 steps, delay = 0 steps, check = no
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 12
  ghost atom cutoff = 12
  binsize = 6, bins = 5 5 5
  2 neighbor lists, perpetual/occasional/extra = 2 0 0
  (1) pair reaxff, perpetual
      attributes: half, newton off, ghost
      pair build: half/bin/ghost/newtoff
      stencil: full/ghost/bin/3d
      bin: standard
  (2) fix qeq/reax, perpetual, copy from (1)
      attributes: half, newton off
      pair build: copy
      stencil: none
      bin: none
Per MPI rank memory allocation (min/avg/max) = 9.558 | 10.17 | 10.77 Mbytes
   Step          Temp          E_pair         E_mol          TotEng         Press     
         0   0             -8505.1816      0             -8505.1816     -673.36566    
      3000   444.67048     -8391.523       0             -8254.9987      831.01498    
Loop time of 5.11957 on 8 procs for 3000 steps with 104 atoms

Performance: 12.657 ns/day, 1.896 hours/ns, 585.986 timesteps/s, 60.943 katom-step/s
96.9% CPU use with 8 MPI tasks x no OpenMP threads

MPI task timing breakdown:
Section |  min time  |  avg time  |  max time  |%varavg| %total
---------------------------------------------------------------
Pair    | 1.6657     | 2.0259     | 2.3838     |  15.3 | 39.57
Neigh   | 0.12553    | 0.14362    | 0.16281    |   3.7 |  2.81
Comm    | 0.38837    | 0.70746    | 1.0534     |  24.9 | 13.82
Output  | 9.4961e-05 | 9.8909e-05 | 0.00012431 |   0.0 |  0.00
Modify  | 2.1825     | 2.2401     | 2.274      |   1.9 | 43.76
Other   |            | 0.002312   |            |       |  0.05

Nlocal:             13 ave          23 max           5 min
Histogram: 1 2 0 1 0 0 3 0 0 1
Nghost:        324.875 ave         377 max         275 min
Histogram: 1 0 1 3 0 0 1 0 0 2
Neighs:         465.75 ave         781 max         125 min
Histogram: 1 1 1 0 1 0 1 1 1 1

Total # of neighbors = 3726
Ave neighs/atom = 35.826923
Neighbor list builds = 300
Dangerous builds not checked
Total wall time: 0:00:05
